[package]
name = "image-filters"
version = "0.1.0"
authors = ["Collins Muriuki <hello@collinsmuriuki.xyz>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
<<<<<<< HEAD
wasm-bindgen = "0.2.84" # pin to  wasm-bindgen = "=0.2.78" if using photon-rs
=======
wasm-bindgen = "=0.2.78"
>>>>>>> solution
# image = "0.25.5"
photon-rs = "0.3.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
